package com.migibert.kheo.core.plugin.network.interfaces;

public enum NetworkInterfaceEventType {
	NETWORK_INTERFACE_REMOVED, 
	NETWORK_INTERFACE_ADDED, 
	NETWORK_INTERFACE_BROADCAST_CHANGED, 
	NETWORK_INTERFACE_ENCAPSULATION_TYPE_CHANGED, 
	NETWORK_INTERFACE_INET6_ADDRESS_CHANGED, 
	NETWORK_INTERFACE_INET4_ADDRESS_CHANGED, 
	NETWORK_INTERFACE_MAC_ADDRESS_CHANGED, 
	NETWORK_INTERFACE_MASK_CHANGED
}
